CREATE DATABASE DRLAVATUDO;
USE DRLAVATUDO;

CREATE TABLE CLIENTE(
ID INT UNSIGNED NOT NULL,
NOME VARCHAR(60) NOT NULL,
EMAIL VARCHAR(80) NOT NULL,
DATA_DE_NASCIMENTO DATE NOT NULL,
TELEFONE_CELULAR CHAR(15) NOT NULL,
TELEFONE_RESIDENCIAL CHAR(14) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE SERVICOS(
ID INT AUTO_INCREMENT NOT NULL, 
NOME_SERVICO VARCHAR(60) NOT NULL, 
VALOR_FINAL DOUBLE(9,2) NOT NULL, 
CUSTO_EMPRESA DOUBLE(9,2) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE ORDEM_DE_SERVICO(
ID INT AUTO_INCREMENT NOT NULL,
ID_CLIENTE INT NOT NULL, 
ID_SERVICO INT NOT NULL, 
DATA_CONTRATACAO DATE NOT NULL, 
DATA_EXECUCAO DATE NOT NULL, 
PRIMARY KEY(ID),
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID),
FOREIGN KEY(ID_SERVICO) REFERENCES SERVICOS(ID)
);

