USE DRLAVATUDO;

CREATE TABLE ORDEM_DE_SERVICO_SERVICOS(
ID INT AUTO_INCREMENT NOT NULL,
ID_ORDEM_DE_SERVICO INT NOT NULL,
ID_SERVICOS INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(ID_ORDEM_DE_SERVICO) REFERENCES ORDEM_DE_SERVICO(ID),
FOREIGN KEY(ID_SERVICOS) REFERENCES SERVICOS(ID)
);

ALTER TABLE ORDEM_DE_SERVICO
DROP COLUMN ID_SERVICO;

