USE DRLAVATUDO;

ALTER TABLE ORDEM_DE_SERVICO_SERVICOS
ADD ENDERECO_RUA VARCHAR(30) NOT NULL,
ADD	ENDERECO_NUMERO INT NOT NULL,
ADD ENDERECO_COMPLEMENTO VARCHAR(10),
ADD ENDERECO_BAIRRO VARCHAR(30) NOT NULL,
ADD ENDERECO_CIDADE VARCHAR(30) NOT NULL,
ADD ENDERECO_ESTADO CHAR(2) NOT NULL;

/* usuário deverá digitar o endereço a cada serviço da ordem de serviço */

SELECT CLIENTE.*, ORDEM_DE_SERVICO.ID, ORDEM_DE_SERVICO.DATA_CONTRATACAO, ORDEM_DE_SERVICO.DATA_EXECUCAO FROM CLIENTE JOIN ORDEM_DE_SERVICO ON ORDEM_DE_SERVICO.ID_CLIENTE = CLIENTE.ID; 